version: '3.1'

services:

  wordpress:
    image: wordpress
    env_file:
      - wordpress.env
    container_name: wordpress
    restart: always
    ports:
      - 8082:80
    volumes:
      - wordpress:/var/www/html
      - ./plugins:/var/www/html/wp-content/plugins/

  db:
    image: mysql:5.7
    env_file:
      - wordpress.env
    restart: always
    volumes:
      - db:/var/lib/mysql

  microa:
    image: microa:microa
    container_name: microa
    restart: always
    ports:
      - 8081:8081
    volumes:
    - microa:/var/lib/micro

  microb:
    image: microb:microb
    container_name: microb
    restart: always
    ports:
      - 8083:8083
    volumes:
    - microb:/var/lib/micro

  microc:
    image: microc:microc
    container_name: microc
    restart: always
    ports:
      - 8084:8084
    volumes:
    - microc:/var/lib/micro

  nginx:
    image: owasp/modsecurity-crs:nginx
    container_name: nginx
    ports:
      - "8088:80"
      - "8443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/templates/conf.d/default.conf.template
      - ./nginx/keys/localhost.pem:/etc/nginx/certs/localhost.pem
      - ./nginx/keys/localhost-key.pem:/etc/nginx/certs/localhost-key.pem
      - ./www:/var/www/html
      - ./nginx/modsec/main.conf:/etc/nginx/modsec/main.conf

    depends_on:
      - wordpress
      - microa
      - microb
      - microc

volumes:
  wordpress:
  db:
  microa:
  microb:
  microc:
